version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cloud_fund_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donorbox_db
      MYSQL_USER: donorbox_user
      MYSQL_PASSWORD: donorbox_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: cloud_fund_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/donorbox_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: cloud_fund_user 
      SPRING_DATASOURCE_PASSWORD: mL6Xuc48KpPPubIEexv0FlIir2ORJ8M0
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      DEBUG: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql_data:
